// List of church options for autocomplete fields across the app
export const churchOptions = [
  'Calvary Chapel Delco',
  'Church of the Saviour',
  'Providence',
  'Valley Creek',
  'Covenant Fellowship',
  'The Journey - Delaware',
  'Valley Point',
  'Tenth Presbyterian',
  'The Block Church',
  '938',
  'Christ Community Church',
  'Faith Reformed Baptist',
  'Aldan Union',
  'Chichester Baptist',
  'Goshen Baptist',
  'Springfield Baptist',
  'Grace Bible Fellowship',
  'Faith Community',
  'The Bridge',
  'The Power Place',
  'Blue Route Vineyard',
  'The Blue Church',
  'Springton Lake Presbyterian',
  'Epic Church Roxborough',
  'Christ Church',
  'Legacy Church',
  'Other',
].sort(); 