name: Build and Deploy sas-ui

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          pwd
          ls
          cd client
          ls
          npm install

      - name: Build React app
        run: |
          pwd 
          ls
          cd client
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: client/build

  deploy-prod:
    name: deploy_prod
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}

      - name: Deploy to Prod server
        run: |
          scp -r build/ ubuntu@3.15.77.70:/var/www/SAS/

      - name: Reload Nginx on Prod
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.15.77.70 "sudo systemctl reload nginx"